list1=['red','green','blue','black','white']
list2=[14,12,36]
print("element of list1:",list1)
print("element of list2",list2)
print("length of list 1 is:",len(list1))
print("length of list 2 is:",len(list2))
list1.insert(2,'pink')
print(list1)
list1.append('yellow')
print("list after apppend",list1)
list2.sort()
print("list 2 after sorting",list2)
list1.remove('blue')
print("list 1 after removing an element",list1)
print("slicing",list1[:4])
print(list[2:4])
list1.reverse()
print("reversed list is:",list1)
list1.extend(list2)
